name: KindDesigns
favicon: null
layout_spectrum: 0.20473764440976083
typography_spectrum: 0.49935316224582493
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.2263431993778795
  lightness: 0.9325212396215647
  saturation: 0.22434688545763493
  rhythmicContrast: 0.011499596759676933
purpose: []
